locations:
- Amsterdam
- Den haag
- Rotterdam
country: Nederland
niches:
- Autopoetsbedrijf
filters:
  has_website: Any
  has_phone: Any
  operational_only: true
scraping:
  max_pages_per_area: 1
  use_neighborhood_splitting: true
  language_code: en
api_limits:
  monthly_request_limit: 1000
output:
  csv_output_dir: output/csv
  include_headers: true
